export const model = [
    {
        index: 0,
        id: 'dd9122ae-a64a-4608-9222-45270497b3f6',
        title: 'AAC Light-heavyweight M1S',
        banner: '/assets/images/raids/dt-m1s.jpg',
        events: [
            {
                source: 'party',
                name: 'Clock Spots - True North',
                offset: '00:01',
                tags: ['position'],
                damageType: 'none',
                notes: 'SUP cardinals. DPS inter-cardinals.',
                id: '7727a9d6-30f2-4f2f-a22f-7a49e4639c28',
            },
            {
                source: 'boss',
                name: 'Quadruple Crossing',
                offset: '00:05',
                tags: ['aoe'],
                damageType: 'Physical',
                notes:
                    'DPS bait 1st strike at inter-cardinals then SUP swap positions with DPS for 2nd strike. On 3rd strike SUP join DPS at cardinals.',
                id: '4b89b37e-b8c4-4761-981c-c3afdd7314e9',
            },
            {
                source: 'boss',
                name: 'Biscuit Maker',
                offset: '00:20',
                tags: ['buster'],
                damageType: 'Physical',
                notes:
                    '2 hit tank buster with a vuln on the 1st hit. Swap or Invul needed.',
                id: '777b086e-2529-4689-a39d-b7f1b0ec1707',
            },
            {
                source: 'boss',
                name: 'Nine Lives',
                offset: '00:35',
                tags: ['buster'],
                damageType: 'Physical',
                notes:
                    'Remember the order of the next attacks the reverse will be safe for Soulshade',
                id: 'b01ae3d8-e6be-431f-b426-f97fc4b05bcf',
            },
            {
                source: 'boss',
                name: 'One-Two Paw',
                offset: '00:47',
                tags: [],
                damageType: 'Physical',
                notes: 'Remember the order of this attack',
                id: 'ba3315fb-fed2-4e3a-b236-f752ad4b4492',
            },
            {
                source: 'boss',
                name: 'Soulshade',
                offset: '01:00',
                tags: [],
                damageType: 'Physical',
                notes:
                    'Move to safe zone. Opposite of the first One-Two Paw for both clones.',
                id: '0cf31064-515d-4c31-8ded-d9766199d63e',
            },
            {
                source: 'boss',
                name: 'One-Two Paw',
                offset: '01:10',
                tags: [],
                damageType: 'Physical',
                notes:
                    'After first strike move to safe zone diagonal from current safe zone.',
                id: 'f8861ab7-e179-46ca-a788-0c2eb9ab8d86',
            },
            {
                source: 'boss',
                name: 'Double / Quadruple Swipe',
                offset: '01:18',
                tags: ['AoE'],
                damageType: 'Physical',
                notes:
                    'If double: light party stack east & west. If quadruple: partner stack at cardinals. The attack will be used at the end of Leaping',
                id: '9892ef51-c8f2-43f1-86fb-b761d4c1d660',
            },
            {
                source: 'boss',
                name: 'Soulshade',
                offset: '01:25',
                tags: [],
                damageType: 'Physical',
                id: '05ab2798-e78c-45d7-80aa-8bbfc6448838',
            },
            {
                source: 'boss',
                name: 'Leaping Quadruple Crossing',
                offset: '01:30',
                tags: ['AoE'],
                damageType: 'Physical',
                id: 'ffac5bdb-87c0-4487-b467-a6838ce660fa',
            },
            {
                source: 'boss',
                name: 'Double / Quadruple Swipe',
                offset: '01:42',
                tags: ['AoE'],
                damageType: 'Physical',
                id: '8633fce5-5216-46cd-9569-928da4784e98',
            },
            {
                source: 'boss',
                name: 'Bloody Scratch',
                offset: '01:52',
                tags: [],
                damageType: 'Physical',
                id: 'bb55b69d-2b64-43ba-94d4-b5e69f10ed24',
            },
            {
                source: 'boss',
                name: 'Mouser',
                offset: '02:10',
                tags: ['AoE'],
                damageType: 'Physical',
                id: '1b062172-98ab-4cee-b8c0-ede8416ad452',
            },
            {
                source: 'boss',
                name: 'Elevate and Eviscerate x 4',
                offset: '02:45',
                tags: [],
                damageType: 'Physical',
                notes:
                    'Take the hit away from the group and position in the inner corner of the tile facing away or outer corner of the tile facing in.',
                id: '0b00ea25-1081-4185-b2cd-702a2375430d',
            },
            {
                source: 'boss',
                name: 'Biscuit Maker',
                offset: '03:33',
                tags: ['buster'],
                damageType: 'Physical',
                notes:
                    '2 hit tank buster with a vuln on the 1st hit. Swap or Invul needed.',
                id: '0d282cb5-a5de-4da7-9557-450a7bf93de5',
            },
            {
                source: 'boss',
                name: 'Shockwave',
                offset: '03:45',
                tags: [],
                damageType: 'Physical',
                id: '49b4795f-2ce3-4f95-9191-ce5998511d38',
            },
            {
                source: 'boss',
                name: 'Grimalkin Gale',
                offset: '03:55',
                tags: ['AoE'],
                damageType: 'Magical',
                id: '04327288-40ab-48ab-a45f-194125a43565',
            },
        ],
    },
    {
        index: 1,
        id: 'aef62d64-fb93-42e2-9e51-efbdaa909273',
        title: 'AAC Light-heavyweight M2S',
        banner: '/assets/images/raids/dt-m2s.jpg',
        events: [],
    },
    {
        index: 2,
        id: 'cc75919f-5a45-4097-b72d-142ea5b136b4',
        title: 'AAC Light-heavyweight M3S',
        banner: '/assets/images/raids/dt-m3s.jpg',
        events: [],
    },
    {
        index: 3,
        id: '4a3f02da-ce42-4e05-805a-9916a3010883',
        title: 'AAC Light-heavyweight M4S',
        banner: '/assets/images/raids/dt-m4s.jpg',
        events: [],
    },
];
