export const model = [
    {
        index: 0,
        id: 'M1S',
        title: 'AAC Light-heavyweight M1S',
        banner: './assets/images/dt-m1s.jpg',
        events: [
            {
                source: 'party',
                name: 'Clock Spots - True North',
                offset: '00:01',
                tags: ['position'],
                damageType: 'none',
                notes: 'SUP cardinals. DPS inter-cardinals.',
            },
            {
                source: 'boss',
                name: 'Quadruple Crossing',
                offset: '00:05',
                tags: ['aoe'],
                damageType: 'Physical',
                notes:
                    'DPS bait 1st strike at inter-cardinals then SUP swap positions with DPS for 2nd strike. On 3rd strike SUP join DPS at cardinals.',
            },
            {
                source: 'boss',
                name: 'Biscuit Maker',
                offset: '00:20',
                tags: ['buster'],
                damageType: 'Physical',
                notes:
                    '2 hit tank buster with a vuln on the 1st hit. Swap or Invul needed.',
            },
            {
                source: 'boss',
                name: 'Nine Lives',
                offset: '00:35',
                tags: ['buster'],
                damageType: 'Physical',
                notes:
                    'Remember the order of the next attacks the reverse will be safe for Soulshade',
            },
            {
                source: 'boss',
                name: 'One-Two Paw',
                offset: '00:47',
                tags: [],
                damageType: 'Physical',
                notes: 'Remember the order of this attack',
            },
            {
                source: 'boss',
                name: 'Soulshade',
                offset: '01:00',
                tags: [],
                damageType: 'Physical',
                notes:
                    'Move to safe zone. Opposite of the first One-Two Paw for both clones.',
            },
            {
                source: 'boss',
                name: 'One-Two Paw',
                offset: '01:10',
                tags: [],
                damageType: 'Physical',
                notes:
                    'After first strike move to safe zone diagonal from current safe zone.',
            },
            {
                source: 'boss',
                name: 'Double / Quadruple Swipe',
                offset: '01:18',
                tags: ['AoE'],
                damageType: 'Physical',
                notes:
                    'If double: light party stack east & west. If quadruple: partner stack at cardinals. The attack will be used at the end of Leaping',
            },
            {
                source: 'boss',
                name: 'Soulshade',
                offset: '01:25',
                tags: [],
                damageType: 'Physical',
            },
            {
                source: 'boss',
                name: 'Leaping Quadruple Crossing',
                offset: '01:30',
                tags: ['AoE'],
                damageType: 'Physical',
            },
            {
                source: 'boss',
                name: 'Double / Quadruple Swipe',
                offset: '01:42',
                tags: ['AoE'],
                damageType: 'Physical',
            },
            {
                source: 'boss',
                name: 'Bloody Scratch',
                offset: '01:52',
                tags: [],
                damageType: 'Physical',
            },
            {
                source: 'boss',
                name: 'Mouser',
                offset: '02:10',
                tags: ['AoE'],
                damageType: 'Physical',
            },
            {
                source: 'boss',
                name: 'Elevate and Eviscerate x 4',
                offset: '02:45',
                tags: [],
                damageType: 'Physical',
                notes:
                    'Take the hit away from the group and position in the inner corner of the tile facing away or outer corner of the tile facing in.',
            },
            {
                source: 'boss',
                name: 'Biscuit Maker',
                offset: '03:33',
                tags: ['buster'],
                damageType: 'Physical',
                notes:
                    '2 hit tank buster with a vuln on the 1st hit. Swap or Invul needed.',
            },
            {
                source: 'boss',
                name: 'Shockwave',
                offset: '03:45',
                tags: [],
                damageType: 'Physical',
            },
            {
                source: 'boss',
                name: 'Grimalkin Gale',
                offset: '03:55',
                tags: ['AoE'],
                damageType: 'Magical',
            },
            /*
                {
                    source: 'boss',
                    name: 'Leaping Quadruple Crossing',
                    offset: '04:47',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Leaping Quadruple Crossing',
                    offset: '04:50',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Leaping Quadruple Crossing',
                    offset: '04:53',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Leaping Quadruple Crossing',
                    offset: '04:56',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Leaping Quadruple Crossing',
                    offset: '05:27',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Nailchipper',
                    offset: '05:27',
                    tags: ['AoE'],
                    damageType: 'Magical',
                },
                {
                    source: 'boss',
                    name: 'Leaping Quadruple Crossing',
                    offset: '05:30',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Leaping Quadruple Crossing',
                    offset: '05:33',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Nailchipper',
                    offset: '05:36',
                    tags: ['AoE'],
                    damageType: 'Magical',
                },
                {
                    source: 'boss',
                    name: 'Leaping Quadruple Crossing',
                    offset: '05:36',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Leaping One-Two Paw',
                    offset: '05:57',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Tempestuous Tear',
                    offset: '05:57',
                    tags: [],
                    damageType: 'Magical',
                },
                {
                    source: 'boss',
                    name: 'Leaping One-Two Paw',
                    offset: '05:59',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Bloody Scratch',
                    offset: '06:11',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Mouser',
                    offset: '06:36',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Mouser',
                    offset: '06:37',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Mouser',
                    offset: '06:39',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Mouser',
                    offset: '06:41',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Mouser',
                    offset: '06:43',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Mouser',
                    offset: '06:45',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Elevate and Eviscerate',
                    offset: '07:08',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Shockwave',
                    offset: '07:09',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Impact',
                    offset: '07:10',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Splintering Nails',
                    offset: '07:10',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Elevate and Eviscerate',
                    offset: '07:20',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Shockwave',
                    offset: '07:21',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Overshadow',
                    offset: '07:22',
                    tags: [],
                    damageType: 'Magical',
                },
                {
                    source: 'boss',
                    name: 'Impact',
                    offset: '07:22',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Elevate and Eviscerate',
                    offset: '07:33',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Shockwave',
                    offset: '07:34',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Overshadow',
                    offset: '07:34',
                    tags: [],
                    damageType: 'Magical',
                },
                {
                    source: 'boss',
                    name: 'Impact',
                    offset: '07:36',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Elevate and Eviscerate',
                    offset: '07:45',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Shockwave',
                    offset: '07:46',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Splintering Nails',
                    offset: '07:47',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Impact',
                    offset: '07:49',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Biscuit Maker',
                    offset: '07:57',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Biscuit Maker',
                    offset: '07:59',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Shockwave',
                    offset: '08:11',
                    tags: [],
                    damageType: 'Magical',
                },
                {
                    source: 'boss',
                    name: 'Grimalkin Gale',
                    offset: '08:14',
                    tags: ['AoE'],
                    damageType: 'Magical',
                },
                {
                    source: 'boss',
                    name: 'Raining Cats',
                    offset: '08:35',
                    tags: ['AoE'],
                    damageType: 'Magical',
                },
                {
                    source: 'boss',
                    name: 'Raining Cats',
                    offset: '08:41',
                    tags: ['AoE'],
                    damageType: 'Magical',
                },
                {
                    source: 'boss',
                    name: 'Raining Cats',
                    offset: '08:47',
                    tags: ['AoE'],
                    damageType: 'Magical',
                },
                {
                    source: 'boss',
                    name: 'Raining Cats',
                    offset: '08:53',
                    tags: ['AoE'],
                    damageType: 'Magical',
                },
                {
                    source: 'boss',
                    name: 'Predaceous Pounce',
                    offset: '09:24',
                    tags: ['AoE'],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Predaceous Pounce',
                    offset: '09:25',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Predaceous Pounce',
                    offset: '09:26',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Predaceous Pounce',
                    offset: '09:27',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'One-Two Paw',
                    offset: '09:29',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'Predaceous Pounce',
                    offset: '09:29',
                    tags: [],
                    damageType: 'Physical',
                },
                {
                    source: 'boss',
                    name: 'One-Two Paw',
                    offset: '09:32',
                    tags: [],
                    damageType: 'Physical',
                },
                */
        ],
    },
    {
        index: 1,
        id: 'M2S',
        title: 'AAC Light-heavyweight M2S',
        banner: './assets/images/dt-m2s.jpg',
    },
    {
        index: 2,
        id: 'M3S',
        title: 'AAC Light-heavyweight M3S',
        banner: './assets/images/dt-m3s.jpg',
    },
    {
        index: 3,
        id: 'M4S',
        title: 'AAC Light-heavyweight M4S',
        banner: './assets/images/dt-m4s.jpg',
    },
];
